server:
  port: 8081
#server:
#  error:
#    include-message: always
#    include-binding-errors: always
#
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/registration?user=siddu
    username: siddu
    password: 1234
#  security:
#    user:
#      name: siddu
#      password: 1234


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

